base_url = "https://donotmisuseai.com"
title = "Do Not Misuse AI"
description = "A Manifesto for Responsible AI"
default_language = "en"

compile_sass = true
build_search_index = false

taxonomies = []

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
github_url = "https://github.com/thelicato/donotmisuseai"
